# CodeRabbit Configuration
# https://docs.coderabbit.ai/guides/configuration

language: ja

reviews:
  # Review profile
  profile: chill

  # Request changes workflow
  request_changes_workflow: false

  # High level summary
  high_level_summary: true

  # Poem in review
  poem: false

  # Review status
  review_status: true

  # Collapse walkthrough
  collapse_walkthrough: false

  # Auto review
  auto_review:
    enabled: true
    drafts: false

  # Path instructions
  path_instructions:
    - path: "**/*.go"
      instructions: |
        - Follow Go best practices and idioms
        - Check for proper error handling
        - Verify goroutine safety
        - Ensure proper resource cleanup (defer)
        - Check for SQL injection vulnerabilities
        - Validate input data

    - path: "**/*.ts"
      instructions: |
        - Follow TypeScript best practices
        - Check for proper type annotations
        - Verify React hooks usage
        - Check for memory leaks in useEffect
        - Ensure proper error boundaries

    - path: "**/*.tsx"
      instructions: |
        - Follow React best practices
        - Check component composition
        - Verify proper key usage in lists
        - Check accessibility (a11y)
        - Ensure responsive design with Tailwind

chat:
  # Auto reply
  auto_reply: true

# Knowledge base
knowledge_base:
  learnings:
    scope: auto
